trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  JAVA_HOME: 'C:\Program Files\Java\jdk-17'
  NEWMAN_HOME: 'C:\Users\sergiomolina\AppData\Roaming\npm\node_modules\newman'
  NODE_HOME: 'C:\Program Files\nodejs'

steps:
- task: Checkout@2
  inputs:
    repository: 'https://github.com/sergiomolber/Anulacion_automatizado.git'
    clean: true

- script: |
    if (Test-Path -Path 'allure-results') {
      Remove-Item -Recurse -Force 'allure-results'
    }
  displayName: 'Limpiar entornos'

- script: |
    $executorContent = @"
    {
        "name": "Azure DevOps",
        "type": "azuredevops",
        "reportName": "Allure Report"
    }
    "@
    $executorContent | Out-File -FilePath 'allure-results/executor.json' -Encoding utf8
  displayName: 'Setup'

- script: |
    $environmentContent = @"
    {
        "Operating System": "Windows",
        "IDE": "Newman y Postman",
        "Environment": "Pruebas"
    }
    "@
    $environmentContent | Out-File -FilePath 'allure-results/environment.json' -Encoding utf8
  displayName: 'Create Environment File'

- script: |
    $newmanPath = "$(NEWMAN_HOME)\newman"
    $testScripts = @(
      "anulacion_happypath.json",
      "Anulacion_401.json",
      "Anulacion_validar_mesageuid.json",
      "Anulacion_transferid.json",
      "anulacion_cambio_ACCEPT.json",
      "anulacion_cambio_PENDING.json",
      "anulacion_estado_vacio.json",
      "Anulacion_sin_enviar.json",
      "Validar_respuestas.json",
      "Anulacion_transferencia_ya_anulada.json"
    )

    foreach ($testScript in $testScripts) {
      try {
        & $newmanPath run $testScript -g globals.json -e environment.json -r allure --insecure
      } catch {
        Write-Host "Error al ejecutar una prueba con Newman: $_"
      }
    }
  displayName: 'Ejecutar Pruebas con Newman'

- script: |
    & "$(NODE_HOME)\node_modules\newman\bin\newman.js" run "anulacion_happypath.json" -g "globals.json" -e "environment.json" -r "allure" --insecure
    & "$(NODE_HOME)\node_modules\newman\bin\newman.js" run "Anulacion_401.json" -d "Errores_401.csv" -g "globals.json" -r "allure" --insecure
    & "$(NODE_HOME)\node_modules\newman\bin\newman.js" run "Anulacion_validar_mesageuid.json" -d "Data_Messageuid.csv" -g "globals.json" -r "allure" --insecure
    & "$(NODE_HOME)\node_modules\newman\bin\newman.js" run "Anulacion_transferid.json" -d "Data_TransferId.csv" -g "globals.json" -r "allure" --insecure
    & "$(NODE_HOME)\node_modules\newman\bin\newman.js" run "anulacion_cambio_ACCEPT.json" -e "environment.json" -g "globals.json" -r "allure" --insecure
    & "$(NODE_HOME)\node_modules\newman\bin\newman.js" run "anulacion_cambio_PENDING.json" -e "environment.json" -g "globals.json" -r "allure" --insecure
    & "$(NODE_HOME)\node_modules\newman\bin\newman.js" run "anulacion_estado_vacio.json" -g "globals.json" -e "environment.json" -r "allure" --insecure
    & "$(NODE_HOME)\node_modules\newman\bin\newman.js" run "Anulacion_sin_enviar.json" -g "globals.json" -r "allure" --insecure
    & "$(NODE_HOME)\node_modules\newman\bin\newman.js" run "Validar_respuestas.json" -g "globals.json" -r "allure" --insecure
    & "$(NODE_HOME)\node_modules\newman\bin\newman.js" run "Anulacion_transferencia_ya_anulada.json" -g "globals.json" -e "environment.json" -r "allure" --insecure
  displayName: 'Ejecutar Pruebas con Newman'

- script: |
    allure generate allure-results --clean
    Rename-Item 'allure-report\index.html' 'Anulacion_report.html'
  displayName: 'Crear reporte html con Newman'

- script: |
    Compress-Archive -Path 'allure-report\Anulacion_report.html' -DestinationPath 'allure-report\Anulacion_report.zip'
  displayName: 'Comprimir Reporte'

- task: SendMail@2
  inputs:
    To: 'molinabernal@gmail.com, svalle@achcolombia.com.co'
    Subject: 'Resultado Microservicios Automatización'
    Body: 'Resultados de la ejecución del lanzamiento de los microservicios de transfiya'
    Attachments: 'allure-report/Anulacion_report.zip'
    From: 'achjenkinsnewman@gmail.com'
  displayName: 'Enviar correo con reporte'
